// import { Party } from '../models/Party'
import { Restaurant } from '../models/Restaurant'

export const party = {
  _id: '64693219ee9df1579ec2426f',
  name: 'Party Time',
  location: 'San Marcos',
  max_distance: 15000,
  number_of_restaurants: 5,
  max_voters: 5,
  type: 'restaurants',
  hours_to_vote_on: [
    {
      id: '8-9 PM',
    },
    {
      id: '9-10 PM',
    },
    {
      id: '10-11 PM',
    },
  ],
  days_to_vote_on: [
    {
      id: 'Monday',
    },
    {
      id: 'Tuesday',
    },
    {
      id: 'Wednesday',
    },
  ],
  vote_on_hours: true,
  vote_on_days: true,
  password: 'ddd',
  restaurants: [
    {
      id: 'MJEwQTtY9mzWJLCU7e25bw',
      alias: 'draft-republic-san-marcos-san-marcos-2',
      name: 'Draft Republic - San Marcos',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/I04V2yKBIZa43hdeGa9DYg/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/draft-republic-san-marcos-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 316,
      categories: [
        {
          alias: 'beergardens',
          title: 'Beer Gardens',
        },
        {
          alias: 'tradamerican',
          title: 'American (Traditional)',
        },
        {
          alias: 'gastropubs',
          title: 'Gastropubs',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.1359,
        longitude: -117.15821,
      },
      transactions: [],
      price: '$$',
      location: {
        address1: '255 Redel Rd',
        address2: null,
        address3: null,
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['255 Redel Rd', 'San Marcos, CA 92078'],
      },
      phone: '+17602903520',
      display_phone: '(760) 290-3520',
      distance: 1853.7821535245944,
      checked: true,
      votes: 0,
    },
    {
      id: '3rqvZnEUbGIuCKHsBWLFLg',
      alias: 'amalfi-cucina-italiana-san-marcos-2',
      name: 'Amalfi Cucina Italiana',
      image_url:
        'https://s3-media3.fl.yelpcdn.com/bphoto/Zwx1mgr9gEc_oIpFG2EfpQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/amalfi-cucina-italiana-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 643,
      categories: [
        {
          alias: 'italian',
          title: 'Italian',
        },
        {
          alias: 'pizza',
          title: 'Pizza',
        },
        {
          alias: 'bars',
          title: 'Bars',
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.12392496202204,
        longitude: -117.20782744781258,
      },
      transactions: ['pickup', 'delivery'],
      price: '$$',
      location: {
        address1: '1035 La Bonita Dr',
        address2: null,
        address3: null,
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['1035 La Bonita Dr', 'San Marcos, CA 92078'],
      },
      phone: '+17606533230',
      display_phone: '(760) 653-3230',
      distance: 3235.8926326354317,
      checked: true,
      votes: 0,
    },
    {
      id: 'PczpdcaqLR9EaGUcbqkS2w',
      alias: 'buona-forchetta-san-marcos-san-marcos-2',
      name: 'Buona Forchetta - San Marcos',
      image_url:
        'https://s3-media3.fl.yelpcdn.com/bphoto/XwaE_HMPYxHsOC7L1WSLCQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/buona-forchetta-san-marcos-san-marcos-2?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 259,
      categories: [
        {
          alias: 'pizza',
          title: 'Pizza',
        },
        {
          alias: 'italian',
          title: 'Italian',
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.13546739553502,
        longitude: -117.1593791,
      },
      transactions: [],
      price: '$$',
      location: {
        address1: '250 N City Dr',
        address2: '',
        address3: null,
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['250 N City Dr', 'San Marcos, CA 92078'],
      },
      phone: '+14425153147',
      display_phone: '(442) 515-3147',
      distance: 1789.2162125697143,
      checked: true,
      votes: 0,
    },
    {
      id: 'SCrEOKR5uKHXo0a4BUsPhA',
      alias: 'aria-restaurant-san-marcos',
      name: 'Aria Restaurant',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/NOhBFyOZjxs78VybGoonkQ/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/aria-restaurant-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 139,
      categories: [
        {
          alias: 'persian',
          title: 'Persian/Iranian',
        },
        {
          alias: 'mediterranean',
          title: 'Mediterranean',
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 33.14891,
        longitude: -117.19797,
      },
      transactions: ['pickup', 'delivery'],
      price: '$$',
      location: {
        address1: '1650 Descanso Ave',
        address2: null,
        address3: '',
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['1650 Descanso Ave', 'San Marcos, CA 92078'],
      },
      phone: '+17605397890',
      display_phone: '(760) 539-7890',
      distance: 2155.7905769225304,
      checked: true,
    },
    {
      id: 'tqjS0NLuXpNQ0D_eeE_ghA',
      alias: 'padadak-san-marcos',
      name: 'Padadak',
      image_url:
        'https://s3-media2.fl.yelpcdn.com/bphoto/q45lb3g-JMqOqmFNeXzi-A/o.jpg',
      is_closed: false,
      url: 'https://www.yelp.com/biz/padadak-san-marcos?adjust_creative=VintRRO4PepUJuYaCM8drQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=VintRRO4PepUJuYaCM8drQ',
      review_count: 56,
      categories: [
        {
          alias: 'korean',
          title: 'Korean',
        },
        {
          alias: 'chicken_wings',
          title: 'Chicken Wings',
        },
      ],
      rating: 4,
      coordinates: {
        latitude: 33.1359,
        longitude: -117.17819,
      },
      transactions: [],
      price: '$$',
      location: {
        address1: '595 Grand Ave',
        address2: 'Ste 105',
        address3: null,
        city: 'San Marcos',
        zip_code: '92078',
        country: 'US',
        state: 'CA',
        display_address: ['595 Grand Ave', 'Ste 105', 'San Marcos, CA 92078'],
      },
      phone: '+17605397104',
      display_phone: '(760) 539-7104',
      distance: 325.364797176378,
      checked: true,
      votes: 0,
    },
  ] as Restaurant[],
  r_votes: {
    MJEwQTtY9mzWJLCU7e25bw: 0,
    '3rqvZnEUbGIuCKHsBWLFLg': 2,
    PczpdcaqLR9EaGUcbqkS2w: 0,
    SCrEOKR5uKHXo0a4BUsPhA: 0,
    tqjS0NLuXpNQ0D_eeE_ghA: 0,
  },
  h_votes: {
    '8-9 PM': 2,
    '9-10 PM': 0,
    '10-11 PM': 0,
  },
  d_votes: {
    '8-9 PM': 2,
    '9-10 PM': 0,
    '10-11 PM': 0,
  },
  r_winner: null,
  h_winner: null,
  d_winner: null,
  voters_so_far: 0,
  createdAt: '2023-05-20T20:48:25.261Z',
  updatedAt: '2023-05-20T20:48:25.261Z',
  __v: 0,
} as any
